name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - type: Android
            os: ubuntu-latest
            build-type: Debug
            task: assembleDebug
            output: android/build/outputs/apk/debug/*

          - type: Android
            os: ubuntu-latest
            build-type: Release
            task: assembleRelease
            output: android/build/outputs/apk/release/*

          - type: Desktop Linux Package
            os: ubuntu-latest
            build-type: Debug
            task: packageDistributionForCurrentOS
            output: desktop/build/compose/binaries/main/*/*

          - type: Desktop Linux Package
            os: ubuntu-latest
            build-type: Release
            task: packageReleaseDistributionForCurrentOS
            output: desktop/build/compose/binaries/main/*/*

          - type: Desktop Linux Distribution
            os: ubuntu-latest
            build-type: Debug
            task: createDistributable
            output: desktop/build/compose/binaries/main/app/**/*

          - type: Desktop Linux Distribution
            os: ubuntu-latest
            build-type: Release
            task: createReleaseDistributable
            output: desktop/build/compose/binaries/main/app/**/*

          - type: Desktop Windows Package
            os: windows-latest
            build-type: Debug
            task: packageDistributionForCurrentOS
            output: desktop/build/compose/binaries/main/*/*

          - type: Desktop Windows Package
            os: windows-latest
            build-type: Release
            task: packageReleaseDistributionForCurrentOS
            output: desktop/build/compose/binaries/main/*/*

          - type: Desktop Windows Distribution
            os: windows-latest
            build-type: Debug
            task: createDistributable
            output: desktop/build/compose/binaries/main/app/**/*

          - type: Desktop Windows Distribution
            os: windows-latest
            build-type: Release
            task: createReleaseDistributable
            output: desktop/build/compose/binaries/main/app/**/*

          - type: Desktop macOS Package
            os: macos-latest
            build-type: Debug
            task: packageDistributionForCurrentOS
            output: desktop/build/compose/binaries/main/*/*

          - type: Desktop macOS Package
            os: macos-latest
            build-type: Release
            task: packageReleaseDistributionForCurrentOS
            output: desktop/build/compose/binaries/main/*/*

          - type: Desktop macOS Distribution
            os: macos-latest
            build-type: Debug
            task: createDistributable
            output: desktop/build/compose/binaries/main/app/**/*

          - type: Desktop macOS Distribution
            os: macos-latest
            build-type: Release
            task: createReleaseDistributable
            output: desktop/build/compose/binaries/main/app/**/*

          - type: Web
            os: ubuntu-latest
            build-type: Debug
            task: jsBrowserDevelopmentWebpack
            output: web/build/distributions/**/*

          - type: Web
            os: ubuntu-latest
            build-type: Release
            task: jsBrowserProductionWebpack
            output: web/build/distributions/**/*
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - if: matrix.type == 'Android'
        uses: android-actions/setup-android@v2
      - name: Write signing config
        run: |
          echo ${{ secrets.KEY }} | base64 --decode > android/key.jks
          echo ${{ secrets.PROPERTIES }} | base64 --decode > android/key.properties
      - name: Build
        run: ./gradlew ${{ matrix.task }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.type }}
          path: ${{ matrix.output }}